### ISSUE TITLE
infrastructure request mail alias

### ISSUE THREAD

**Issue by benoitc** [erlef/infra-wg#3]
as we just discussed today, let's create a mail where members can contact us for their infrastructure needs.

I propose to have request-infra@erlef.org. I'm unsure if it should be an alias to main group mail or if we shouldn't setup an account for it. Thought?

**Comment by starbelly** [comment]
I think a separate account makes sense if we want to separate general discussion from requests.

**Comment by starbelly** [comment]
@benoitc I wonder if [topicbox](https://www.topicbox.com/) may be a good interface for requests, what do you think?

**Comment by starbelly** [comment]
We might want to consider zendesk or something similar as well. Using a mailbox is good as it's nice and low tech, but there are some cons there... We have to make sure we're responding as `infra-request@` etc. There's room for deleting history as well. 

 Some pros to zendesk would be avoiding the two little problems above as well as having some integrations for the infra group (slack, etc.). 

Thoughts?

**Comment by starbelly** [comment]
For now and to get the show on the road, I think it should be `infra-requests@` and it should be an inbox. We should follow this protocol with it: 

 - A request comes into the inbox. 
 - The inbox has a rule to send a copy of the message to our group
 - When the group receives a message, the first person who will take action on the request must reply to the group stating such so that we don't have a dead lock of sorts. 
 - The volunteer who stated they would take action processes the request. 
 - The volunteer is to use the requests inbox and address to respond to all inbound communications, including threads of a request for continuity and privacy purposes. 
 - The volunteer is then to update the group stating they processed the request once it is complete. 

We can look at formal tools later to decide if this is warranted. 

Edit: Note that we will have to use  infra.requests@erlef.org since fastmail doesn't allow `-` in usernames for inboxes.

**Comment by starbelly** [comment]
https://github.com/erlef/infra-wg/wiki/Request-Protocol
